//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace solicitudescooitza.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSolicitudes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblSolicitudes()
        {
            this.TblSolicitudesCatRubros = new HashSet<TblSolicitudesCatRubros>();
            this.TblSolicitudesPendientes = new HashSet<TblSolicitudesPendientes>();
        }
    
        public long idTblSolicitudes { get; set; }
        public Nullable<long> idCatProveedores { get; set; }
        public Nullable<int> idTblUsuarioModificado { get; set; }
        public Nullable<long> idCatRubros { get; set; }
        public Nullable<long> idCatEstados { get; set; }
        public Nullable<long> idCatTipoSolicitud { get; set; }
        public Nullable<long> idTblUsuario { get; set; }
        public string observaciones { get; set; }
        public string observacionesAutorizacion { get; set; }
        public string observacionesLiquidacion { get; set; }
        public Nullable<long> cantidad { get; set; }
        public string lugarDestinoComision { get; set; }
        public string lugarOrigenComision { get; set; }
        public string motivoComision { get; set; }
        public string tipoTransaccion { get; set; }
        public string imagenTransaccion { get; set; }
        public string numeroCuenta { get; set; }
        public Nullable<decimal> rembolsoReintegro { get; set; }
        public Nullable<decimal> montoTotal { get; set; }
        public Nullable<decimal> totalQuetzales { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> monto { get; set; }
        public string imagen { get; set; }
        public string razon { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaAlta { get; set; }
    
        public virtual CatEstados CatEstados { get; set; }
        public virtual CatProveedores CatProveedores { get; set; }
        public virtual CatRubros CatRubros { get; set; }
        public virtual CatRubros CatRubros1 { get; set; }
        public virtual CatTipoSolicitud CatTipoSolicitud { get; set; }
        public virtual TblUsuarios TblUsuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSolicitudesCatRubros> TblSolicitudesCatRubros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSolicitudesPendientes> TblSolicitudesPendientes { get; set; }
    }
}
