//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace solicitudescooitza.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSolicitudesCatRubros
    {
        public long idTblSolicitudesCatRubros { get; set; }
        public Nullable<long> idTblSolicitudes { get; set; }
        public Nullable<long> idCatRubros { get; set; }
        public Nullable<long> idCatProveedores { get; set; }
        public Nullable<long> idCatEstados { get; set; }
        public string detalle { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<System.DateTime> fechaFactura { get; set; }
        public Nullable<long> cantidad { get; set; }
        public string imagen { get; set; }
        public Nullable<System.DateTime> fechaAlta { get; set; }
        public Nullable<long> idTblUsuarios { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<long> idTblUsuarioModifica { get; set; }
    
        public virtual CatProveedores CatProveedores { get; set; }
        public virtual CatRubros CatRubros { get; set; }
        public virtual TblSolicitudes TblSolicitudes { get; set; }
    }
}
